sudo: required
language: node_js
node_js:
  - 16

services:
  - docker
before_install:
  - docker build -t react-app -f Dockerfile.dev .
script:
  - docker run -e CI=true react-app npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" ### AWS region of your choice
  app: "react-app" ### Your EB App name
  env: "Reactapp-env" ### Your EB App environment name
  bucket_name: "elasticbeanstalk-us-east-1-375607314637" ### S3 bucket name
  bucket_path: "EBApptest" ### S3 folder name under S3 bucket above
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
